language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9

install:
  - pip install -r requirements_dev.txt
  - pip install .
script:
  - py.test --cov=workflows
after_success:
  - coveralls

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password --pro
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mgerstel
  password:
    secure: DG9W01GpzBDs80rOsHCXyrOBLSc2f2sOco5UekMN8Xa7J2yDjHQsMLjCn69gw2v/kPHkqq+/ttBf8ToMLrzs1QqS3BMIF4FmDKuD6e2Yd7FDDk1QstvnwCimq4DasbrHVYIPt09iZajfqidnPSjqZapcYmiaCrE/PKHClSDLriixybU+SaizDBm9Uu+1mw5QqUwUYwKUcd3o/3vpmrGQqr9na9XEUQyTHEwmAGl4mAPrZoiJSIWP8hWDHAR/Ysb0DMK+2GnNRgXPedMW/ms/EBNwSEhi9xCFo3iiZmrYAkvmENUYl4F61DFC6IeMyNMfIIm5rCRHeroxf5bHchVXvoBzSUmTdfmJ98bRgOE2ShXmckiMXz3qvcCL5HlXPwd4+NZ8W7WcSAbGKr7w0lCLX999d+y84ujhCtQf+qzqHlJx1AV7+4V6lUeC8onHnNVOB6N6ijsmo5kZZMfma3Vo6UKMxzyH40lpc0g+LL/uJKyU6muNYpM5tPjn3bYOGjBMNSwX8VmgVBXg8ShEWwB4n+l0RHg3oKpEidbaRdgRDHHvvjRNbqYB9J1CxX1eaX5a2vXAVM//gJgV1JhAQqlAvbMp3CFr06isHzn9NjhpCjSETW2j80JUcOzt/u9fnnRnWVt3zRvwATDxFRbMqFc8xFCAh6IzlU4mbPU8W6RkKL4=
  on:
    tags: true
    repo: DiamondLightSource/python-workflows
    python: 3.9
