language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
install:
  - pip install .
  - pip install 'pytest>=2.9' pytest-cov pytest-timeout coveralls
script:
  - py.test --cov=workflows
after_success:
  - coveralls
